### PR TITLE
Section 1 copyedit

### PR DESCRIPTION
**Pull request by ajeanmahoney**

### CODE REVIEW

**Comment by chriswendt** [comment]
Thanks for the detailed clarification of the text, it all looks good to me.

**Comment by chriswendt** [comment]
Hi Jean,

I accepted the pull requests, but having trouble figuring out how to merge in the main branch.  Not sure if i should have done that for each pull request or not, i had to fix conflicts for the subsequent pull requests, but it looks like they are on new branches so i probably didn’t do that the best way :) 

So, help would be appreciated :)

-Chris

**Comment by chriswendt** [comment]
Actually i figured it out, all of the pull requests are now merged into main branch.  But maybe double check to make sure i didn’t screw anything up :)

-Chris

**Comment by ajeanmahoney** [comment]
@chriswendt It all looks good! 
You can check the overall diff here: 
https://ajeanmahoney.github.io/sipcore-callinfo-rfc/#go.draft-ietf-sipcore-callinfo-rcd.diff

**Pull request merged**
